---
title: "Sanger Sequencing Report"
author: "Kory Melton"
date: "9/30/2019"
output: word_document
csl: bioinformatics.csl
bibliography: references.bib
---

# Background

<!-- Example Citation
Previous work has looked at the microbial biogeography of university campuses and found high diversity [@ross2015microbial].
End of Example Citation -->
I was given 40 sequences of 16S ranging from 5-1,310 bases long in ab1 format. The primary aims of this analysis were to assess sequence usability, quality, and length for the 16S sequences. After cleaning the data, BLAST matches were found against NCBI's GenBank and phylogenetic BLAH



# Methods

<!-- Bulleted list of what was conducted
    -- Clean/Trim Sequences
    -- Sequence usability
        -- Geneious Prime
    -- BLAST
    -- Alignment (MAFFT)
    -- Phylogenies
        -- PhyML
        -- Mr Bayes
-->

I used Geneious Prime (v 2019.2.1) to trim, clean, asses the quality of sequences, create a multiple sequence alignment from trimmed reads

## Sequence Cleaning

I used Geneious Prime (v 2019.2.1) to trim, clean, and assess the quality of sequences. Sequences ends were trimmed to reduce low quality on the ends of sequences. Trimming was done conservatively. Bases were trimmed if they contained any baseline contamination, low peaks, messy peaks, or if the peaks began to span multiple nucleotide positions with only one clear peak. After trimming, I assessed the usability of the sequences, separating them into four groups: very good, average, poor, and unuseable. Very good sequences had long stretches (more than 100 base pairs) of high quality reads. Very good sequences were cleaned to change any internally miscalled bases and add associated ambiguity codes. Average sequences had mostly high quality reads without long stretches. Poor sequences had some high quality reads, but overall looked messy. Unuseable sequences were either very short (5 base pairs), or had multiple peaks throughout the sequence. 

## Sequence Alignment

I used the MAFFT [@katoh2002mafft] multiple sequence aligner to align the trimmed, very good 16S sequences. The 6 sequences were aligned with a 16S sequence from *Thermus aquaticus*

## Phylogeny

I used two approaches (Maximum Likelihood and Bayesian) to make phylogenetic inferences of the six very good sequences. I created a Maximum Likelihood phylogeny using the PhyML algorithm [@guindon2009estimating]. I built a Bayesian phylogeny using the MrBayes 3.6.2 algorithm [@huelsenbeck2001mrbayes].

## BLAST

All sequences rated very good, average, or poor were used to search for BLAST matches in NCBI's GenBank database [@benson2000genbank]. All BLAST searches were done using the highly similar sequences (megablast) algorithm. All matches were selected by choosing which species was most represented at the top of the list. 

# Results

## Sequences and Alignments

| Locus 	| Original Filename   	| Corrected Filename             	| Usability 	| Length after Trimming 	| Number of Corrected Bases 	|
|-------	|---------------------	|--------------------------------	|-----------	|-----------------------	|---------------------------	|
| 16S   	| AFM3_27f_C01.ab1    	| AFM3_27f_C01_KM_cleaned.ab1    	| useable   	| 613                   	| 3                         	|
| 16S   	| P_1_27f_G04.ab1     	| P_1_27f_G04_KM_cleaned.ab1     	| useable   	| 797                   	| 0                         	|
| 16S   	| MCU17_27f_B08.ab1   	| MCU17_27f_B08_KM_cleaned.ab1   	| useable   	| 653                   	| 1                         	|
| 16S   	| AF5_27f_E06.ab1     	| AF5_27f_E06_KM_cleaned.ab1     	| useable   	| 404                   	| 1                         	|
| 16S   	| EM1-9_27F_C05.ab1   	| EM1-9_27f_C05_KM_cleaned.ab1   	| useable   	| 608                   	| 5                         	|
| 16S   	| MCU12_27f_F07.ab1   	| MCU12_27f_F07_KM_cleanedab1.   	| useable   	| 695                   	| 0                         	|
| 16S   	| PC4A_27f_C10.ab1    	| PC4A_27f_C10_KM_trimmed.ab1    	| useable   	| 562                   	| 1                         	|
| 16S   	| PC3A_27f_A10.ab1    	| PC3A_27f_A10_KM_trimmed.ab1    	| useable   	| 241                   	| 0                         	|
| 16S   	| CVC1B_27f_B03.ab1   	| CVC1B_27f_B03_KM_trimmed.ab1   	| useable   	| 461                   	| 0                         	|
| 16S   	| SB3_27f_C06.ab1     	| SB3_27f_C06_KM_trimmed.ab1     	| useable   	| 147                   	| 0                         	|
| 16S   	| P3_27f_C08.ab1      	| P3_27f_C08_KM_trimmed.ab1      	| useable   	| 467                   	| 1                         	|
| 16S   	| CVC7A_27f_E02.ab1   	| CVC7A_27f_E02_KM_trimmed.ab1   	| useable   	| 621                   	| 1                         	|
| 16S   	| CSB3B_27f_F10.ab1   	| CSB3B_27f_F10_KM_trimmed.ab1   	| useable   	| 239                   	| 0                         	|
| 16S   	| CLS6_27f_F04.ab1    	| CLS6_27f_F04_KM_trimmed.ab1    	| useable   	| 516                   	| 0                         	|
| 16S   	| FL2A_27f_A09.ab1    	| FL2A_27f_A09_KM_trimmed.ab1    	| useable   	| 383                   	| 0                         	|
| 16S   	| Cntrl_2_27f_D05.ab1 	| Cntrl_2_27f_D05_KM_trimmed.ab1 	| useable   	| 410                   	| 0                         	|
| 16S   	| I5_27f_D10.ab1      	| I5_27f_D10_KM_trimmed.ab1      	| useable   	| 268                   	| 0                         	|
| 16S   	| 16A_C_27f_F03.ab1   	| 16A_C_27f_F03_KM_trimmed.ab1   	| useable   	| 672                   	| 0                         	|
| 16S   	| M3_2_27f_B01.ab1    	| M3_2_27f_B01_KM_trimmed.ab1    	| useable   	| 258                   	| 0                         	|
| 16S   	| 3A-B_27f_B04.ab1    	| 3A-B_27f_B04_KM_trimmed.ab1    	| useable   	| 836                   	| 1                         	|
| 16S   	| CLS2_27f_B04.ab1    	| CLS2_27f_B04_KM_trimmed.ab1    	| useable   	| 246                   	| 0                         	|
| 16S   	| PC1B_27f_A06.ab1    	| PC1B_27f_A06_KM_trimmed.ab1    	| useable   	| 907                   	| 0                         	|
| 16S   	| CLS1_27f_E04.ab1    	| CLS1_27f_E04_KM_unusable.ab1   	| unusable  	| 271                   	| 0                         	|
| 16S   	| UE3B_27f_G09.ab1    	| UE3B_27f_G09_KM_unusable.ab1   	| unusable  	| 685                   	| 0                         	|
| 16S   	| EN_27f_F02.ab1      	| EN_27f_F02_KM_unusable.ab1     	| unusable  	| 492                   	| 0                         	|
| 16S   	| I6_27f_C10.ab1      	| I6_27f_C10_KM_unusable.ab1     	| unusable  	| 746                   	| 0                         	|
| 16S   	| CSB3A_27f_E10.ab1   	| CSB3A_27f_E10_KM_unusable.ab1  	| unusable  	| 733                   	| 0                         	|
| 16S   	| M2_2_27f_D01.ab1    	| M2_2_27f_D01_KM_unusable.ab1   	| unusable  	| 269                   	| 0                         	|
| 16S   	| EVM3_27f_C08.ab1    	| EVM3_27f_C08_KM_unusable.ab1   	| unusable  	| 455                   	| 0                         	|
| 16S   	| D6_27f_B09.ab1      	| D6_27f_B09_KM_unusable.ab1     	| unusable  	| 317                   	| 0                         	|
| 16S   	| D3_27f_G08.ab1      	| D3_27f_G08_KM_unusable.ab1     	| unusable  	| 608                   	| 0                         	|
| 16S   	| CVCWA_27f_A02.ab1   	| CVCWA_27f_A02_KM_unusable.ab1  	| unusable  	| 386                   	| 0                         	|
| 16S   	| b1b_27f_B02.ab1     	| b1b_27f_B02_KM_unusable.ab1    	| unusable  	| 267                   	| 0                         	|
| 16S   	| IF3_27f_E07.ab1     	| IF3_27f_E07_KM_unusable.ab1    	| unusable  	| 5                     	| 0                         	|
| 16S   	| EVN_27f_A02.ab1     	| EVN_27f_A02_KM_unusable.ab1    	| unusable  	| 5                     	| 0                         	|
| 16S   	| EVM2_27f_G01.ab1    	| EVM2_27f_G01_KM_unusable.ab1   	| unusable  	| 5                     	| 0                         	|
| 16S   	| E1_27f_B02.ab1      	| E1_27f_B02_KM_unusable.ab1     	| unusable  	| 5                     	| 0                         	|
| 16S   	| D1_27f_E08.ab1      	| D1_27f_E08_KM_unusable.ab1     	| unusable  	| 5                     	| 0                         	|
| 16S   	| CLS5_27f_A05.ab1    	| CLS5_27f_A05_KM_unusable.ab1   	| unusable  	| 5                     	| 0                         	|
| 16S   	| APP1_27f_G09.ab1    	| APP1_27f_G09_KM_unusable.ab1   	| unusable  	| 5                     	| 0                         	|

## Phylogenies

## BLAST Results

<!-- Notes on BLAST
    -- AFM3_27f_C01: definitely staphylococcus sp.
                     best hit was capitis, but was mixed with    epidermidis
    -- PC4A_27f_C10: confident in neisseria sp.
                    - perflava
                    - flavescens
                    - subflava
    -- PC3A_27f_C10: confident in neisseria sp.
                    - perflava
                    -subflava
    -- CVC1B_27f_B03: confident in bacteria
                    -pantoea
                    -gamma proteobacterium
    -- CSB3B_27f_F10: confident in enterobacteriaceae
                    -klebsiella sp.
                    -raoultella sp.
    -- CLS6_27f_F04: relatively few hits (8)
                    -confident in bacteria
    -- 3A-B_27f_B04: confident in pseudomonas sp.
    -- CLS2_27f_B04: relatively few hits (8)
-->

| Sequence        	| Description                                   	| Percent Identity (%) 	| Query Cover (%) 	| Accession  	| E-value 	|
|-----------------	|-----------------------------------------------	|----------------------	|-----------------	|------------	|---------	|
| AFM3_27f_C01    	| Staphylococcus capitis partial                	| 99.51                	| 100             	| LT978442.1 	| 0.0     	|
| P_1_27f_G04     	| Staphylococcus hominis strain WS1-7           	| 100.00               	| 100             	| MN448417.1 	| 0.0     	|
| MCU17_27f_B08   	| Staphylococcus epidermidis strain 15          	| 99.85                	| 100             	| MK465356.1 	| 0.0     	|
| AF5_27f_E06     	| Staphylococcus hominis strain WS3-1           	| 99.75                	| 100             	| MN448433.1 	| 0.0     	|
| EM1-9_27f_C05   	| Bacillus licheniformis strain XIXJ053         	| 99.18                	| 100             	| MH801084.1 	| 0.0     	|
| MCU12_27f_F07   	| Brevundimonas vesicularis strain A33          	| 100.00               	| 100             	| MN252083.1 	| 0.0     	|
| PC4A_27f_C10    	| Neisseria perflava strain 17-P17              	| 99.82                	| 100             	| MF374824.1 	| 0.0     	|
| PC3A_27f_A10    	| Neisseria perflava strain 17-P17              	| 99.59                	| 100             	| MF374824.1 	| 1e-119  	|
| CVC1B_27f_B03   	| Pantoea sp. strain ST18.17/028                	| 100.00               	| 100             	| MK875130.1 	| 0.0     	|
| SB3_27f_C06     	| Stapholococcus epidermidis strain IBK-11      	| 100.00               	| 100             	| MN428237.1 	| 3e-69   	|
| P3_27f_C08      	| Bacillus licheniformis strain Xuyi_293_3      	| 98.93                	| 100             	| MN309987.1 	| 0.0     	|
| CVC7A_27f_B03   	| Enterobacteriaceae bacterium X6/SB50          	| 98.87                	| 100             	| LC007901.1 	| 0.0     	|
| CSB3B_27f_F10   	| Klebsiella granulomatis strain 2-7-8          	| 100.00               	| 99              	| JF91986.1  	| 4e-119  	|
| CLS6_27f_F04    	| Uncultured bacterium partial                  	| 100.00               	| 91              	| FM162220.1 	| 5e-17   	|
| FL2A_27f_A09    	| Steptococcus salivarius strain JF             	| 98.96                	| 100             	| CP014144.1 	| 0.0     	|
| Cntrl_2_27f_D05 	| Escherichia coli stain NCTC9040               	| 97.80                	| 100             	| LR134247.1 	| 0.00    	|
| I5_27f_D10      	| Pseudomonas sp. strain 273                    	| 94.12                	| 100             	| MK681820.1 	| 3e-111  	|
| 16A_C_27f_F03   	| Escherichia coli strain SJA92                 	| 92.12                	| 100             	| MN147836.1 	| 0.0     	|
| M3_2_27f_B01    	| Bacillus licheniformis strain FMB2-2          	| 96.86                	| 98              	| KP992871.1 	| 1e-115  	|
| 3A-B_27f_B04    	| Pseudomonas sp. m8                            	| 83.46                	| 33              	| DQ219815.1 	| 6e-58   	|
| CLS2_27f_B04    	| Uncultured Paenibacillus sp. clone R7SP1T1H06 	| 94.63                	| 98              	| HQ018234.1 	| 2e-103  	|
| PC1B_27f_A06    	| Neisseria sp. strain CMUL044                  	| 85.55                	| 96              	| MK258031.1 	| 4e-168  	|


# Discussion

# Sources Cited
